spring.application.name: brewing

logging:
  level.org.springframework.cloud: DEBUG
  level.org.springframework.cloud.sleuth: TRACE
  level.org.springframework.cloud.sleuth.log: DEBUG
  level.org.springframework.cloud.sleuth.trace: DEBUG
  level.org.springframework.cloud.sleuth.instrument.rxjava: DEBUG

server.port: ${PORT:9992}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/brewing.log

spring.cloud.stream:
  binder.rabbit.default.maxConcurrency: 5


endpoints.health.sensitive: false
endpoints.default.web.enabled: true
management.security.enabled: false
management.endpoints.web.base-path: /

spring.zipkin.sender.type: web
spring:
  sleuth:
    propagation-keys:
      - test-communication-type

# The bean 'presenting.FeignClientSpecification', defined in null, 
# could not be registered. A bean with that name has already been defined in null and overriding is disabled.
spring.main.allow-bean-definition-overriding: true

spring.cloud.function.definition: events
spring.cloud.stream.bindings.events-out-0.destination: events
